### ISSUE TITLE
can't add a code to a theme or remove theme

### ISSUE THREAD

**Issue by xabigar** [onekin/WebAnnotatorSPL#3]
when you do a rigth click over a theme name, doesn't appear the options to add a code or remove a theme

**Comment by haritzmedina** [comment]
Hi @xabigar. I've been trying to reproduce this issue. I tried with the following configurations and it works well:
- Only theme
- Theme + Code
(I would like to share with you the configuration file of the generated product, but I couldn't). You can try with ReviewAndGo for example.

Can you give me further information to get to the problem? Or is the issue already solved in any of the latest updates?

**Comment by xabigar** [comment]
I think that the problem has been solved in one of the commits

**Comment by rmedeiros** [comment]
I have reproduced this issue in HighLight&Go product. It happens when you reload the page with a theme with children.
